name: Deploy

on:
  push:
    branches:
      - 'test/*'

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install && yarn build
        env:
          CI: true
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
